### ISSUE TITLE
$t_prefix not correctly initialised

### ISSUE THREAD

**Issue by TheLimey** [webforward/PHP-IMAP-Sync#2] opened 2018-05-02 17:47 UTC
On line 31 you conditionally set the $t_prefix variable, but if that doesn't go through the variable is not set, causing an error when it is referenced later:

`if (preg_match('/}INBOX/',$t_folders[0]['name'],$m)) $t_prefix = 'INBOX';`

I added a line after this to set it to an empty string if not to 'INBOX':

`if (preg_match('/}INBOX/',$t_folders[0]['name'],$m)) $t_prefix = 'INBOX';`
`else $t_prefix = '';`

**Comment by mrl22** [comment] 2020-09-30 15:04
Duplicate of #3

**Closed by mrl22** 2020-09-30 15:05 UTC
